### PR TITLE
Remove hardcoding of FTP for storage

### PR DESCRIPTION
**Pull request by lancepioch**
Remove hardcoding of FTP for storage, keep it as default though

### CODE REVIEW

**Comment by yoginth** [comment]
working fine!

**Comment by yoginth** [comment]
I Have installed voten on my dev system (Ubuntu 16) when I create a new post in voten the images are being delivered through cdn.voten.co instead of localhost, I have changed everything in .env file and filesystem.php in config. please help me with fixing this issue!

**Comment by lancepioch** [comment]
@yoginth My changes are most likely out of date. Unfortunately the author has no plans to support or merge this anytime soon.

**Comment by yoginth** [comment]
Awesome!

**Pull request merged**
