### PR TITLE
add seeders, IDE helpers, centralizing variables and fixing typos and sentry setup, social login improvement

### PR DESCRIPTION
**Pull request by Chinese1904**
Love this project, first off.

I was doing some work on my local end to make it more universal and more easily editable. What this pull request includes

1. It adds seeders for an admin users and it sets the appropriate role.
2. Fixes sentry setup and adds a 500 error view
3. centralizes same universal variables and fixed typos. It would make more sense eventually to utilize translations more, but for the time being it should be a start.
4. added an IDE helper only on local development (didn't mean to actually pull this, but no time to revert it haha and figured that it actually would make sense and would not hurt.)
5. Only show social logins if those variables are set

If you want me to split up the pull request, let me know. In case you wanna use all of it. Great :-)

### CODE REVIEW

**Comment by sullyfischer** [comment]
wow, you put some serious time on it. You're awesome! Since there are a lot of changes, separate PRs would be make it easier and same me time. 

Quick note: I like the idea of settings.php file, but it still has to fetch the values from the .env file, otherwise everybody have to add it to their .ignore file and we don't want that. (We're using the exact master branch on production). 

Thanks again!

**Comment by Chinese1904** [comment]
Sure, I will send in different PRs later. In order to make it a little easier and instead of changing two files, why not store those files in a settings table as JSON variables and create a settings tab with some input fields in the admin panel to change them?

**Comment by sullyfischer** [comment]
Well to me it's more of "why do we?!" question. Using `.env` files does the job right now, and there's a long ToDo list ahead of us.

**Comment by Chinese1904** [comment]
Let me know what's on the list so I can see where I can help out.

The reason I thought about centralizing some of the information is so that for new users, especially the ones fairly new to developing, it would be much easier to modify some of the variables. But editing the .env file and maybe a settings.php file seems easy enough.

**Comment by sullyfischer** [comment]
Could be great if we could discuss these kind of things on [/c/votendev](https://voten.co/c/votendev) so maybe others could join us. After all Voten's a community! (and it does support markdown)

At the top of my head, there's this issue:
Laravel's notifications data formats for broadcast driver and database driver are different. This causes an error when a notification is broadcasted. But after a refresh user can load the same notification and it works just fine (because this time it's being fetched from database). 

The production server however is working fine now and that's because back then I used to push /vendor files and in my local vendors files I've done this modification in Laravel core that takes care of it:
In `BroadcastNotificationCreated.php`:

```
    /**
     * Get the data that should be sent with the broadcasted event.
     *
     * @return array
     */
    public function broadcastWith()
    {
        return [
        	'data' => $this->data,
            'id' => $this->notification->id,
            'type' => get_class($this->notification),
            'created_at' => Carbon::now(),
            'read_at' => null
        ];

        // return array_merge($this->data, [
        //     'id' => $this->notification->id,
        //     'type' => get_class($this->notification),
        // ]);
    }
```

Can you think of a "right way" for this?

**Pull request closed without merging**
