### PR TITLE
Updated response error codes

### PR DESCRIPTION
**Pull request by peanut24**
I feel the 500 error codes are not applicable, as there was no internal server error. Updated the response codes to 422 to indicate an unprocessable entity

### CODE REVIEW

**Comment by sullyfischer** [comment]
I manually merged your PR also did the releated front-end code for it. I'm thinking we're also need to do this change in other places of the app. Thanks for noticing it!

**Comment by sullyfischer** [comment]
To be honest, I'm not good with all the REST API stuff.

**Comment by peanut24** [comment]
We all have out area of expertise. Appropriate response codes are just a little pet hate of mine. I have some experience building apis, for companies like smirnoff, so let me know if there is anything I can contribute

**Comment by sullyfischer** [comment]
At some point we're gonna have to release a public (I'm guessing REST)API. I could use your help. Thanks again!

**Pull request closed without merging**
