### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Gwill**

### CODE REVIEW

**Comment by sullyfischer** [comment]
Heey, thanks for the PR. 
Could you please explain to me why we need fideloper/proxy?
Also, could you please describe changes in the `app/Console/Kernel.php` as well? 

Thanks

**Comment by Gwill** [comment]
Hi, adding fideloper/proxy package and fixing `app/Console/Kernel.php` are wish to be closer to the laravel 5.5 starter structure, and if running Voten behind some load balance app it is feel good working with fideloper/proxy.

**Comment by sullyfischer** [comment]
I read about the load balancer thing. I still don't get it. Could you give me an example of where it can be useful? I heard about the issue of the file driver for sessions when behind a load balancer. But since we're using the cookie driver, that's not an issue for us. I wanna know what else is there to worry abt. Thanks

**Comment by sullyfischer** [comment]
Hey man, my hands are kinda full at the moment, but I will take a look at this PR and merge it. It's a great one.

**Comment by Gwill** [comment]
sorry, I will rebase this pr later.

**Comment by sullyfischer** [comment]
@Gwill thanks mate

**Comment by yoginth** [comment]
PR Looks more **Complicated**!

**Comment by yoginth** [comment]
what is the use of it? please explain in detail!

**Comment by yoginth** [comment]
I Changed all those things in my repo too! but I didn't see any updates on performance!

**Pull request closed without merging**
