### PR TITLE
Feature/live-nested-comments

### PR DESCRIPTION
**Pull request by darorl89**
Comments positioning for new comments is fixed. Works for both hot and new sort type, we should look for top comments aswell. Needs proper testing though.

### CODE REVIEW

**Comment by darorl89** [comment]
Hey, I think you missed it, Voten have live comments for yourself. Nested comments from others did not work, now they do. Please check.

**Comment by sullyfischer** [comment]
I just rechecked it on https://voten.co/c/test/just-some-submission-for-testing and it works just fine. Did you test it on your dev machine?

**Comment by darorl89** [comment]
I just checked, and it's different case. Code in comment.vue handles user's comment only. Code I added handles others' nested comments adding. I did not know about the code in comment.vue so probably need to add some ifs.

**Comment by darorl89** [comment]
Ok, I have just checked and indeed there is a code for it already. BUT it seems to work randomly, despite event being received by the comment component itself. There is some kind of problem here. So either you leave it as it is or check my solution and comment out old one for now.
You should just compare both of them.

**Comment by darorl89** [comment]
`this.list.children.unshift(comment);`
This line in comment.vue seems unreliable. despite event is always properly dispatched to the comment.
Doing the same in my solution but in submissionpage.vue, digging through comments by recursively seems to work reliably, plus you do not need to check ifs for every comment, only in worse case, but do as you wish.

**Comment by sullyfischer** [comment]
Your solution is also good. I leave the current code be as I don't see any benefits in replacing it. Thanks for your work. You can use the #test channel for doing your tests on the platform to prevent duplicate work in the future. 

I appreciate the time you're spending on the platform.

**Comment by darorl89** [comment]
Actually, I've been digging through the code to understand how it works and it turned out that is just Vue not catching changes in this.list.children (Comment.vue) sometimes, or catching it with huge delay. I left it as it is for now, but that should be fixed eventually.

**Comment by sullyfischer** [comment]
It's working just fine in my tests. If you believe otherwise, provide an example test that would break it.

**Pull request closed without merging**
